#开发环境配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.179.60:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: blog
    password: xxwdbb58
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志级别
logging:
  level:
    root: info
    com.yanjin: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080